### ISSUE TITLE
JSON format for exitcode could be simplified

### ISSUE THREAD

**Issue by haxtibal** [Icinga/icinga-powershell-apichecks#6]
The JSON `exitcode` attribute from a `/v1/checker?command=foo` response is a bit nasty to deserialize in statically typed languages, because its type varies in uncommon way:
- if a command can be executed, the real exit code is propagated like `{"excitcode": 0}`, i.e. _integer_
- if a command is not available for execution, we get `{"excitcode": {}}`, i.e. _empty object_

Integer has no empty form. A better representation would IMO be `integer or null`. This could be deserialized out of the box to e.g. `Optional<int>`.

**Comment by LordHepipud** [comment]
Thank you for the issue. Honestly the exit code should be 3 in case something fails, to always be able to return UNKNOWN.
I believe there is some error with handling errors properly.
